<a href="https://colab.research.google.com/github/ysn-gachon/AI-Class-202335225-nayeonsu/blob/main/Week4/titanic_attempt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic.csv')
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,1.0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,0.0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,0.0

In [60]:
y=df['Survived']
y.value_counts()
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [61]:
X=df.drop(['Survived', 'Name', 'Ticket', 'Cabin'] ,axis=1)



X.head()

   PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1       3    0  22.0      1      0   7.2500       0.0
1            2       1    1  38.0      1      0  71.2833       1.0
2            3       3    1  26.0      0      0   7.9250       0.0
3            4       1    1  35.0      1      0  53.1000       0.0
4            5       3    0  35.0      0      0   8.0500       0.0

In [62]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [63]:
X_train

     PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
105          106       3    0  28.0      0      0   7.8958       0.0
68            69       3    1  17.0      4      2   7.9250       0.0
253          254       3    0  30.0      1      0  16.1000       0.0
320          321       3    0  22.0      0      0   7.2500       0.0
706          707       2    1  45.0      0      0  13.5000       0.0
..           ...     ...  ...   ...    ...    ...      ...       ...
835          836       1    1  39.0      1      1  83.1583       1.0
192          193       3    1  19.0      1      0   7.8542       0.0
629          630       3    0   NaN      0      0   7.7333       2.0
559          560       3    1  36.0      1      0  17.4000       0.0
684          685       2    0  60.0      1      1  39.0000       0.0

[668 rows x 8 columns]

In [64]:
X_test

     PassengerId  Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
495          496       3    0   NaN      0      0   14.4583       1.0
648          649       3    0   NaN      0      0    7.5500       0.0
278          279       3    0   7.0      4      1   29.1250       2.0
31            32       1    1   NaN      1      0  146.5208       1.0
255          256       3    1  29.0      0      2   15.2458       1.0
..           ...     ...  ...   ...    ...    ...       ...       ...
167          168       3    1  45.0      1      4   27.9000       0.0
306          307       1    1   NaN      0      0  110.8833       1.0
379          380       3    0  19.0      0      0    7.7750       0.0
742          743       1    1  21.0      2      2  262.3750       1.0
10            11       3    1   4.0      1      1   16.7000       0.0

[223 rows x 8 columns]

In [65]:
y_train

105    0
68     1
253    0
320    0
706    1
      ..
835    1
192    1
629    0
559    1
684    0
Name: Survived, Length: 668, dtype: int64

In [66]:
y_test

495    0
648    0
278    0
31     1
255    1
      ..
167    0
306    1
379    0
742    1
10     1
Name: Survived, Length: 223, dtype: int64

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [68]:
from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.7802690582959642
[[113  26]
 [ 23  61]]

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Radom Forest ---
0.8430493273542601
[[126  13]
 [ 22  62]]